import java.io.FileInputStream
import java.util.Properties

plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

// Release signing — loaded from android/key.properties when present.
// If the file is missing (CI without secrets, fresh clone for debug-only
// work), release builds fall back to the debug keys so `flutter run
// --release` still works locally without forcing every contributor to
// configure signing.
val keystoreProperties =
    Properties().apply {
        val f = rootProject.file("key.properties")
        if (f.exists()) {
            load(FileInputStream(f))
        }
    }
val hasReleaseKeystore = keystoreProperties.getProperty("storeFile") != null

// ── Network security config ──────────────────────────────────────────────────
//
// The self-hosted relay and update host is a personal server, and this
// repository is public, so its address is a build input like the signing key —
// never a checked-in literal. Android still needs a cleartext exception for it
// (the app talks plain HTTP/WS to a bare IP: a certificate would need a domain,
// and the app rejects self-signed ones), so the config is generated for the
// build from `REMOTE_PI_HOSTS` (comma/space separated) and compiled from a
// build-only res directory. Everything else keeps requiring TLS.
//
// Without the variable the file still exists — with no exceptions at all — so a
// plain clone builds, ships, and simply cannot reach a self-hosted server. That
// is the right default for a repository anyone can clone.
val remotePiHosts: List<String> =
    (System.getenv("REMOTE_PI_HOSTS") ?: "")
        .split(',', ' ', '\n')
        .map { it.trim() }
        .filter { it.isNotEmpty() }

val generateNetworkSecurityConfig by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/remotePi/res/xml")
    val hosts = remotePiHosts
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().asFile.resolve("network_security_config.xml")
        file.parentFile.mkdirs()
        file.writeText(
            buildString {
                appendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>")
                appendLine("<!-- GENERATED by app/android/app/build.gradle.kts from REMOTE_PI_HOSTS — do not edit. -->")
                appendLine("<network-security-config>")
                appendLine("    <base-config cleartextTrafficPermitted=\"false\" />")
                if (hosts.isNotEmpty()) {
                    appendLine("    <domain-config cleartextTrafficPermitted=\"true\">")
                    hosts.forEach { appendLine("        <domain includeSubdomains=\"false\">$it</domain>") }
                    appendLine("    </domain-config>")
                } else {
                    appendLine("    <!-- No REMOTE_PI_HOSTS at build time: no cleartext exceptions. -->")
                }
                appendLine("</network-security-config>")
            },
        )
    }
}

tasks.named("preBuild").configure { dependsOn(generateNetworkSecurityConfig) }

android {
    namespace = "work.jacobmoura.remotepi"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    // The cleartext exceptions are generated per build (see the task above).
    sourceSets["main"].res.srcDir(layout.buildDirectory.dir("generated/remotePi/res"))

    defaultConfig {
        applicationId = "work.jacobmoura.remotepi"
        // plan/23 § "Versão mínima Android" — the remote_pi_identity
        // plugin requires API 34 (Block Store + modern biometry), so
        // the app inherits the same floor. Bump intentional, recorded
        // in the plano.
        minSdk = 34
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    signingConfigs {
        if (hasReleaseKeystore) {
            create("release") {
                keyAlias = keystoreProperties.getProperty("keyAlias")
                keyPassword = keystoreProperties.getProperty("keyPassword")
                storeFile = rootProject.file(keystoreProperties.getProperty("storeFile"))
                storePassword = keystoreProperties.getProperty("storePassword")
            }
        }
    }

    buildTypes {
        release {
            signingConfig =
                if (hasReleaseKeystore) {
                    signingConfigs.getByName("release")
                } else {
                    signingConfigs.getByName("debug")
                }
        }
    }

    // Distribute arm64 only. Flutter's `--target-platform` limits
    // libapp.so/libflutter.so, but prebuilt AARs (MLKit's
    // libbarhopper_v3.so, CameraX, dartjni) ship all three ABIs and would
    // otherwise add ~9 MB no arm64 device ever loads. `ndk.abiFilters` does
    // not strip those, so exclude them at packaging time. Debug is left
    // alone so x86_64 emulators still run.
    packaging {
        jniLibs {
            excludes.add("lib/armeabi-v7a/**")
            excludes.add("lib/x86/**")
            excludes.add("lib/x86_64/**")
        }
    }
}

flutter {
    source = "../.."
}

dependencies {
    // 16 KB page-size compliance (Google Play, enforced since Nov 2025).
    // mobile_scanner 5.2.3 pulls ML Kit + CameraX whose prebuilt native libs
    // are only 4 KB-aligned (libbarhopper_v3.so, libimage_processing_util_jni.so),
    // which Play now rejects. Force the newer, 16 KB-aligned releases — Gradle
    // version-conflict resolution picks these over mobile_scanner's transitive
    // 17.2.0 / 1.3.3. No Dart-side scanner API change. CameraX modules are kept
    // on one matching version to avoid cross-module runtime mismatches.
    implementation("com.google.mlkit:barcode-scanning:17.3.0")
    implementation("androidx.camera:camera-core:1.4.2")
    implementation("androidx.camera:camera-camera2:1.4.2")
    implementation("androidx.camera:camera-lifecycle:1.4.2")
}
